'use client';

import { useEffect } from "react";
import { usePathname } from "next/navigation";
import Head from "next/head";

const Metadata = () => {
  const pathname = usePathname();
  const isPlatformRoute = pathname && pathname.includes('/platform');

  useEffect(() => {
    if (isPlatformRoute) {
      document.title = "Bohemian | Plataforma";
    } else {
      document.title = "Bohemian";
    }
  }, [isPlatformRoute]);

  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>
  );
};

export default Metadata;