"use client";

import { useEffect } from "react";
import { usePathname } from "next/navigation";
import Head from "next/head";

const Metadata = () => {
  const pathname = usePathname();

  useEffect(() => {
    document.title = "Ezequiel M. Tartaglia | Portfolio";
  }, []);

  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
    </Head>
  );
};

export default Metadata;
